name: Deploy Frontend
on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t smaragda2/docker-learn -f Dockerfile.dev .
      - run: docker run -e CI=true smaragda2/docker-learn npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Docker-Course
          environment_name: Docker-Course-env
          existing_bucket_name: elasticbeanstalk-us-east-2-767828742387
          region: us-east-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip